name: flutter_application_7
description: "A new Flutter project."
publish_to: 'none' # Prevents accidental publishing to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.6.0

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  material_design_icons_flutter: ^7.0.7296

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.13.1 # Only keep flutter_launcher_icons
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - images/

# Keep only flutter_launcher_icons configuration
flutter_launcher_icons:
  android: true
  ios: true
  image_path: "./images/doctors.png"  # Path to your launcher icon image
